### ISSUE TITLE
Database Manager not accessible

### ISSUE THREAD

**Issue by jimmybanegas** [junariltd/junari-odoo-docker#1]
Hi, I'm using the docker image and I set up both the Odoo and Postgres using Docker. Everything looks good but I'm getting The **database manager has been disabled by the administrator** upon login.

Any ideas @dupski ? I already tried overriding the 'db_list' flag, but it still doesn't let me "Create a database" even though I already have one created folowing the steps in the readme.

![image](https://user-images.githubusercontent.com/2421080/90275983-61d6ac80-de20-11ea-8a19-cd7277150c22.png)

**Comment by dupski** [comment]
Hi @jimmybanegas93 - I believe this will be the db_filter setting. We use hostnames to select which DB to launch.

You can either access your database using DBNAME.localhost (may require a hosts file entry) or set db_filter to the empty string.

Let us know how you get on!

**Comment by jimmybanegas93** [comment]
> Hi @jimmybanegas93 - I believe this will be the db_filter setting. We use hostnames to select which DB to launch.
> 
> You can either access your database using DBNAME.localhost (may require a hosts file entry) or set db_filter to the empty string.
> 
> Let us know how you get on!

I am a bit confused about where to use either of them, I tried adding **--db-filter** in the launch.json described in your post here: https://medium.com/@dupski/creating-and-installing-your-first-odoo-module-using-docker-and-visual-studio-code-41ebdfd362e4 but nothing has worked. I'm also use the .env file you mention, so maybe I've to put it there?

**Comment by jimmybanegas** [comment]
> Hi @jimmybanegas93 - I believe this will be the db_filter setting. We use hostnames to select which DB to launch.
> 
> You can either access your database using DBNAME.localhost (may require a hosts file entry) or set db_filter to the empty string.
> 
> Let us know how you get on!

Thanks for the help, I fixed it editing **/etc/odoo/odoo.conf** as follows:

![image](https://user-images.githubusercontent.com/2421080/90319418-20fc9780-def5-11ea-9710-a03f50ec6af9.png)

It's working now, this is great! @dupski

**Comment by dupski** [comment]
Cool. I'll have a look at changing the default to make this easier in future :)

**Comment by jimmybanegas** [comment]
> Cool. I'll have a look at changing the default to make this easier in future :)

Sounds good!
