### ISSUE TITLE
odoo - database manager disabled

### ISSUE THREAD

**Issue by gaskmemo** [junariltd/junari-odoo-docker#3]
Hi, I am having trouble to initialize Odoo, because I am getting this error:

"The database manager has been disabled by the administrator"

Hope you can help me with this issue

Thanks in advanced

**Comment by dupski** [comment]
Hi @gaskmemo - we disable the database manager by default as it is a bit of a security risk to have enabled by default.

If you want to enable it, you need to set `list_db = True` in the odoo configuration file. Theres some hints on doing this [here](https://github.com/junariltd/junari-odoo-docker/blob/master/README.md#overriding-odoo-configuration-settings).

It is pretty easy to create a new database directly via the command line though, as described [here](https://github.com/junariltd/junari-odoo-docker/blob/master/README.md#creating-a-database-and-running-the-image)

Have fun :)
